[package]
name = "viewer_slint"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
slint = "1.8.0"
rfd = "0.15.4"
plotters = "0.3.7"
colorgrad = "0.7.2"
[build-dependencies]
slint-build = "1.8.0"

