[package]
name = "extract_high_amplitudes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.41", features = ["derive"] }
geo = "0.30.0"
serde = "1.0.219"
serde_json = "1.0.143"
shared = { path = "../shared" }
